### ISSUE TITLE
Using kubeaudit as a Go package isn't possible since ClientOptions is in an internal package 

### ISSUE THREAD

**Issue by eschley** [Shopify/kubeaudit#347] opened 2021-07-23 11:22 UTC
##### ISSUE TYPE
 - [X] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
The kubeaudit auditors AuditLocal and AuditCluster both require a parameter of ClientOptions that is defined in
"github.com/Shopify/kubeaudit/internal/k8s" which can't be used outside of kubeaudit itself.

### Steps To Reproduce
1. create a new project NOT a test under kubeaudit project.
2. copy the example code for a Local or Cluster audit from https://pkg.go.dev/github.com/Shopify/kubeaudit
3. try to run it and you will get this error "use of internal package github.com/Shopify/kubeaudit/internal/k8s not allowed"

##### ENVIRONMENT
* Kubeaudit version: main / latest
* Kubeaudit install method: DIY-BUILD

##### STEPS TO REPRODUCE
1. Create a new project, not a test in the kubeaudit package
2. Copy the code examples for AuditCluster or AuditLocal from https://pkg.go.dev/github.com/Shopify/kubeaudit
3. Try to compile your project.  You will get the following error "use of internal package github.com/Shopify/kubeaudit/internal/k8s not allowed"

##### EXPECTED RESULTS
Should be able to use kubeaudit as a package
ClientOptions needs to be moved out of the internal package in order for kubeaudit to be used as a Go package.

**Comment by genevieveluyt** [comment] 2021-07-26 14:01
Closing this as a duplicate of https://github.com/Shopify/kubeaudit/issues/298. Feel free to reopen if you disagree!

**Closed by genevieveluyt** 2021-07-26 14:01 UTC

**Comment by genevieveluyt** [comment] 2021-07-26 15:38
Should be fixed by https://github.com/Shopify/kubeaudit/pull/348
